using System.Windows.Input;
using System.Collections.ObjectModel; using System.Diagnostics; using System.Windows; using Microsoft.Extensions.Configuration; using Microsoft.Win32; using ProformaViewer.Models; using ProformaViewer.Services;
namespace ProformaViewer;
public partial class MainWindow : Window {
 readonly ExcelReaderService excel=new(); readonly PdfExportService pdf=new(); readonly ObservableCollection<ProformaEntry> all=new(); readonly IConfiguration config;
 public MainWindow(){InitializeComponent(); config=new ConfigurationBuilder().SetBasePath(AppContext.BaseDirectory).AddJsonFile("appsettings.json",false,true).Build();}
 async void Database_Click(object sender,RoutedEventArgs e){var fleet=(string)((FrameworkElement)sender).Tag; var path=config[$"Databases:{fleet}"]??""; SetBusy(true,$"Loading {fleet}…"); try {var rows=await excel.ReadAsync(path); all.Clear(); foreach(var x in rows)all.Add(x); ItemsList.ItemsSource=all; ShowList(fleet); StatusText.Text=$"{rows.Count} items loaded from {System.IO.Path.GetFileName(path)}";}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to load database",MessageBoxButton.OK,MessageBoxImage.Error);StatusText.Text="Database unavailable";}finally{SetBusy(false);}}
 void ShowList(string fleet){HomePanel.Visibility=Visibility.Collapsed;ItemsList.Visibility=Visibility.Visible;SearchBox.Visibility=Visibility.Visible;SelectAllButton.Visibility=Visibility.Visible;ClearButton.Visibility=Visibility.Visible;ExportButton.Visibility=Visibility.Visible;HomeButton.Visibility=Visibility.Visible;SubTitle.Text=$"{fleet} • select one or more proformas";}
 void Home_Click(object s,RoutedEventArgs e){ItemsList.Visibility=SearchBox.Visibility=SelectAllButton.Visibility=ClearButton.Visibility=ExportButton.Visibility=HomeButton.Visibility=Visibility.Collapsed;HomePanel.Visibility=Visibility.Visible;SubTitle.Text="Choose a fleet database";SearchBox.Text="";StatusText.Text="Ready";}
 void Search_TextChanged(object s,System.Windows.Controls.TextChangedEventArgs e){var q=SearchBox.Text.Trim();ItemsList.ItemsSource=string.IsNullOrEmpty(q)?all:new ObservableCollection<ProformaEntry>(all.Where(x=>x.Title.Contains(q,StringComparison.OrdinalIgnoreCase)||x.FileName.Contains(q,StringComparison.OrdinalIgnoreCase)));}
 void SelectAll_Click(object s,RoutedEventArgs e){foreach(var x in ItemsList.Items.Cast<ProformaEntry>())x.IsSelected=true;UpdateCount();}
 void Clear_Click(object s,RoutedEventArgs e){foreach(var x in all)x.IsSelected=false;UpdateCount();}
 void Selection_Click(object s,RoutedEventArgs e)=>UpdateCount();
 void UpdateCount(){var n=all.Count(x=>x.IsSelected);ExportButton.IsEnabled=n>0;StatusText.Text=$"{n} selected";}
 async void Export_Click(object s,RoutedEventArgs e){var chosen=all.Where(x=>x.IsSelected).ToList();var dlg=new SaveFileDialog{Filter="PDF files (*.pdf)|*.pdf",FileName=$"Combined Proformas {DateTime.Now:yyyy-MM-dd HHmm}.pdf",AddExtension=true,DefaultExt=".pdf"};if(dlg.ShowDialog()!=true)return;SetBusy(true,"Exporting pages…");Progress.Visibility=Visibility.Visible;var p=new Progress<int>(v=>Progress.Value=v);try{var r=await pdf.ExportAsync(chosen,dlg.FileName,p);StatusText.Text=$"Export complete: {r.PageCount} pages";var message=$"Created {r.PageCount}-page PDF."+(r.Errors.Count>0?$"\n\nWarnings:\n{string.Join("\n",r.Errors)}":"");if(MessageBox.Show(message+"\n\nOpen the PDF now?","Export complete",MessageBoxButton.YesNo,r.Errors.Count>0?MessageBoxImage.Warning:MessageBoxImage.Information)==MessageBoxResult.Yes)Process.Start(new ProcessStartInfo(dlg.FileName){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"Export failed",MessageBoxButton.OK,MessageBoxImage.Error);}finally{Progress.Visibility=Visibility.Collapsed;SetBusy(false);UpdateCount();}}
 void SetBusy(bool busy,string? text=null){ExportButton.IsEnabled=!busy&&all.Any(x=>x.IsSelected);if(text!=null)StatusText.Text=text;System.Windows.Input.Mouse.OverrideCursor=busy?System.Windows.Input.Cursors.Wait:null;}
}
