using System.Collections.ObjectModel;using System.Diagnostics;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Media;using Microsoft.Extensions.Configuration;using Microsoft.Win32;using ProformaViewer.Models;using ProformaViewer.Services;
namespace ProformaViewer;
public partial class MainWindow:Window
{
 readonly ExcelReaderService excel=new();readonly FrequencyChartService chart=new();readonly PdfExportService pdf=new();readonly ObservableCollection<ProformaEntry> entries=new();readonly IConfiguration config;string? databasePath;string? fleet;
 public MainWindow(){InitializeComponent();WindowState=WindowState.Maximized;config=new ConfigurationBuilder().SetBasePath(AppContext.BaseDirectory).AddJsonFile("appsettings.json",false,true).Build();ItemsList.ItemsSource=entries;for(var i=1;i<=24;i++)FrequencyBox.Items.Add(new ComboBoxItem{Content=$"X{i:00}"});}
 async void Database_Click(object s,RoutedEventArgs e){fleet=(string)((FrameworkElement)s).Tag;var path=config[$"Databases:{fleet}"]??"";SetBusy(true,$"Loading {fleet}...");try{var rows=await excel.ReadAsync(path);entries.Clear();foreach(var row in rows)entries.Add(row);databasePath=path;ShowList(fleet);StatusText.Text=$"{rows.Count} items loaded";}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to load database",MessageBoxButton.OK,MessageBoxImage.Error);}finally{SetBusy(false);}}
 void ShowList(string f){HomePanel.Visibility=Visibility.Collapsed;ItemsList.Visibility=SelectAllButton.Visibility=ClearButton.Visibility=ExportButton.Visibility=FleetButton.Visibility=FolderButton.Visibility=Visibility.Visible;var at200=f=="AT200";FrequencyBox.Visibility=EditChartButton.Visibility=at200?Visibility.Visible:Visibility.Collapsed;FrequencyBox.SelectedIndex=0;SubTitle.Text=$"{f} | select one or more proformas";InstructionText.Text="Click anywhere on a tile to select or deselect it";}
 async void FrequencyBox_SelectionChanged(object s,SelectionChangedEventArgs e){if(fleet!="AT200"||FrequencyBox.SelectedIndex<=0)return;var f=(FrequencyBox.SelectedItem as ComboBoxItem)?.Content?.ToString();if(f==null)return;SetBusy(true,$"Loading {f}...");try{var tasks=await Task.Run(()=>chart.GetTasks(f));ItemsList.UnselectAll();foreach(var item in entries.Where(x=>tasks.Contains(x.TaskCode)))ItemsList.SelectedItems.Add(item);StatusText.Text=$"{ItemsList.SelectedItems.Count} proformas selected for {f}";}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to load AT200 frequency",MessageBoxButton.OK,MessageBoxImage.Error);}finally{SetBusy(false);}}
 void EditChart_Click(object s,RoutedEventArgs e){try{Process.Start(new ProcessStartInfo(FrequencyChartService.LocalFilePath){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"Unable to open frequency file",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void ItemsList_PreviewMouseLeftButtonDown(object s,MouseButtonEventArgs e){var item=Parent<ListBoxItem>(e.OriginalSource as DependencyObject);if(item==null)return;item.IsSelected=!item.IsSelected;e.Handled=true;}static T? Parent<T>(DependencyObject? o)where T:DependencyObject{while(o!=null){if(o is T t)return t;o=VisualTreeHelper.GetParent(o);}return null;}
 void Home_Click(object s,RoutedEventArgs e){ItemsList.UnselectAll();ItemsList.Visibility=SelectAllButton.Visibility=ClearButton.Visibility=ExportButton.Visibility=FleetButton.Visibility=FolderButton.Visibility=FrequencyBox.Visibility=EditChartButton.Visibility=Visibility.Collapsed;HomePanel.Visibility=Visibility.Visible;fleet=databasePath=null;}
 void Folder_Click(object s,RoutedEventArgs e){var folder=System.IO.Path.GetDirectoryName(databasePath);if(folder!=null)Process.Start(new ProcessStartInfo("explorer.exe",$"\"{folder}\""){UseShellExecute=true});}
 void SelectAll_Click(object s,RoutedEventArgs e)=>ItemsList.SelectAll();void Clear_Click(object s,RoutedEventArgs e){FrequencyBox.SelectedIndex=0;ItemsList.UnselectAll();}void ItemsList_SelectionChanged(object s,SelectionChangedEventArgs e){ExportButton.IsEnabled=ItemsList.SelectedItems.Count>0;StatusText.Text=$"{ItemsList.SelectedItems.Count} selected";}
 async void Export_Click(object s,RoutedEventArgs e){var d=new SaveFileDialog{Filter="PDF files (*.pdf)|*.pdf",FileName=$"Combined Proformas {DateTime.Now:yyyy-MM-dd HHmm}.pdf"};if(d.ShowDialog()!=true)return;SetBusy(true,"Exporting...");try{var r=await pdf.ExportAsync(ItemsList.SelectedItems.Cast<ProformaEntry>(),d.FileName);MessageBox.Show($"Created {r.PageCount}-page PDF.","Export complete");}catch(Exception ex){MessageBox.Show(ex.Message,"Export failed");}finally{SetBusy(false);}}
 void SetBusy(bool b,string? t=null){if(t!=null)StatusText.Text=t;Mouse.OverrideCursor=b?Cursors.Wait:null;}
}
